### ISSUE TITLE
What is AUX?

### ISSUE THREAD

**Issue by amironof** [tehniq3/TEF6686#2]
Hello!
What is AUX here?
![image](https://user-images.githubusercontent.com/85175550/221809330-48f03eca-672d-4897-885f-afb3042bcc20.png)
Tnx

**Comment by tehniq3** [comment]
hello,

AUX is just a provision (reserve) for future design... an connector (not
used)

BR,
Nicu

În mar., 28 feb. 2023 la 11:23, amironof ***@***.***> a scris:

**Comment by amironof** [comment]
Thanks a lot.
And can u write what is it?
![image](https://user-images.githubusercontent.com/85175550/221842709-0ef5b0fa-8d89-4d91-949e-0c897c230058.png)

**Comment by tehniq3** [comment]
yes, are connectors for power the sistem and for 5V as reserve..

..............................................................................................................




În mar., 28 feb. 2023 la 13:37, amironof ***@***.***> a scris:
