### ISSUE TITLE
hd44780 library

### ISSUE THREAD

**Issue by amironof** [tehniq3/TEF6686#3]
Hello! Can you help me please?
What hd44780 library I need to install from list at the left side.
Thank you.
![telegram-cloud-photo-size-2-5348316654389545394-y](https://user-images.githubusercontent.com/85175550/234226945-56228514-9d36-40af-b66b-c47bb4298390.jpg)

**Comment by tehniq3** [comment]
this sketch (ino file) is not in this repository ... where you find it ?

**Comment by amironof** [comment]
Sorry, i was wrong
