### ISSUE TITLE
Firmware for Nano

### ISSUE THREAD

**Issue by amironof** [tehniq3/TEF6686#4]
Hello!
Do you have TEF6686 firmware for Arduino Nano?

**Comment by tehniq3** [comment]
sure. pleace check article: https://nicuflorica.blogspot.com/2020/07/radio-fm-rds-cu-tef6686-si-arduino-nano.html

**Comment by amironof** [comment]
Thanks a lot!

**Comment by amironof** [comment]
And what .ino file is for LCD2004?
[This file](https://github.com/tehniq3/TEF6686/blob/master/radio_stailus_scroll.ino) does not fit to my Nano:
`Compilation error: data section exceeds available space in board`

Do you have .ino for Nano with LCD2004?

Thanks a lot

**Comment by tehniq3** [comment]
yes, if you look in article is LCD2004... first sketch is https://github.com/tehniq3/TEF6686/blob/master/tef6686_rds_stailus.ino and seconds sketch is https://github.com/tehniq3/TEF6686/blob/master/radio_stailus_scroll.ino 
in line 29, respectively in line 30 is: LiquidCrystal_I2C lcd(0x3F,20,4); witch means: LCD20x4 with 0x3F adress on i2c... why is not clear???? 
I compiled the sketch with Arduino 1.8.19 for Arduino Nano with ATmega328P and messages is:
Sketch uses 20310 bytes (66%) of program storage space. Maximum is 30720 bytes.
Global variables use 1766 bytes (86%) of dynamic memory, leaving 282 bytes for local variables. Maximum is 2048 bytes.
Low memory available, stability problems may occur.

**Comment by amironof** [comment]
Sorry, I'm not so good in Arduino.
And these sketches are working without additional libraries such as TEF6686.h or Tuner_Api.h, aren't it?

Thank you very much!

**Comment by tehniq3** [comment]
no, no. you need just or first sketch ( https://github.com/tehniq3/TEF6686/blob/master/tef6686_rds_stailus.ino ) or second sketch ( https://github.com/tehniq3/TEF6686/blob/master/radio_stailus_scroll.ino ) but with it need to install libraries, as comment you can find links:

#include <Encoder.h> // from http://www.pjrc.com/teensy/td_libs_Encoder.html
#include <LiquidCrystal_I2C.h>  // https://github.com/fdebrabander/Arduino-LiquidCrystal-I2C-library

**Comment by amironof** [comment]
Both of files are not working at my Nano :(
Perhaps you have experience, how it can be fixed?

![telegram-cloud-photo-size-2-5379780588367628764-y](https://user-images.githubusercontent.com/85175550/236438366-a88f4900-d185-4d40-850a-a1be7b566bff.jpg)

**Comment by tehniq3** [comment]
looks like LCD is on other i2c address.. try 0x27 instead 0x3F.. 
LiquidCrystal_I2C lcd(0x27,20,4); // instead of LiquidCrystal_I2C lcd(0x3F,20,4); 
if not work search as in articles: https://learn.adafruit.com/scanning-i2c-addresses/arduino or https://www.hackster.io/abdularbi17/how-to-scan-i2c-address-in-arduino-eaadda

**Comment by amironof** [comment]
It works! Thanks a lot!
